apiVersion: skaffold/v2beta27
kind: Config
metadata:
  name: skaffold-buildah
build:
  artifacts:
  - image: buildah-example
    context: ./examples/buildah
    buildah:
      containerfile: Dockerfile
      compression: "gzip"
  local:
    push: false

deploy:
  kubectl:
    manifests:
    - examples/buildah/pod.yaml